development:
  adapter: postgresql
  encoding: utf8
  database: votweb_development
  pool: 5
  username: postgres
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: votweb_test
  pool: 5
  username: postgres
  min_messages: WARNING
  host: localhost
  template: template0
